services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports: 
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
  
  user_service:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules/
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: db
      DATABASE_HOST: postgres
      SECRET: huehuehuehueh

